[Argument]
  [[Argument.Set]]
    Arg = "proj"
    Value = "ebay-mailer"
    Help = "Allows you to define a proj"
  [[Argument.Set]]
    Arg = "something"
    Value = "4"
    Help = "Allows you to define a something"

[Required]
  Commands = [
    "echo 'here is the: {{proj}}'",
    "echo 'here is the: {{something}}'"
  ]
  Hosts = ["blade-prod-a"]
[Overrides] 
  Concurrency = 5