[Required]
  Commands = [
    "hostname",
    "pwd",
    "echo 'sleeping for 2 secs' && sleep 2",
    "echo 'hello world'",
    "date"
  ]
  HostLookupCommand = "python knife node search prod"
[Overrides] 
  Concurrency = 5