[Required]
  # At a minimum you need a command.
  Commands = [
    "hostname"
  ]

  # And a predifined list of hardcoded hosts.
  Hosts = ["blade-dev", "blade-prod", "blade-integ"]

[Overrides]
  # But you can specifiy a concurrency limit (default 1)
  Concurrency = 3

  HostLookupCacheDisabled = false
  HostLookupCacheDuration = "5m"

  # And a login user (default root)
  User = "root"

[Resilience]
  WaitDuration = "5s"
  Retries = 3
  RetryBackoffStrategy = "Exponential"
  RetryBackoffMultiplier = "5s"
  FailBatch = true

[Help]
  Short = "Does something cool"
  Long = "This recipe does something cool and also makes sure to blah...blah...blah. Also it's supposed to ensure that blah blah and so you can be assured that it works great."
  Usage = "boom"

[Interaction]
  Banner = "Are you sure you want to continue?"
  PromptBanner = true
  PromptColor = "red"