[[commands]]
blade = "shoddy-deploy"
concurrency = 5
command = "sudo apt-get update && sudo apt-get install shoddy && sudo service restart"

[[commands]]
blade = "shoddy-restart"
concurrency = 15
command = "sudo service restart"
hosts = "ips %env% shoddy"
