[Argument]
  [[Argument.Set]]
    Arg = "name"
    Value = "Bob"
    Help = "is the name to echo"
    
[Required]
  Commands = [
    "echo '{{name}}'",
    "hostname"
  ]
  Hosts = ["blade-prod", "blade-prod-a"]

[Overrides] 
  Concurrency = 2